name: AchievmentSystem
version: 1.0
main: de.illegalaccess.achievmentsystem.AchievmentSystem
api-version: 1.16
authors: [ IllegalAccess ]
description: This is a Plugin for Custom Achievment
commands:
  AdminAchievment:
  Achievment: